export { default as Sidebar } from './sidebar/Sidebar';
export { default as Main } from './Main/Main';
export { default as Paper } from './Paper/Paper';
export { default as UniversityCard } from './UniversityCard/UniversityCard';
export { default as TutorList } from './Tutors/TutorsList';
export { default as Section } from './Section/Section';
export { default as GeneralCardList } from './GeneralCard/GeneralCardList';
export { default as Button } from './Button/Button';
export { default as TutorForm } from './Forms/TutorForm';